---
title: "Fragility Analysis"
author: "Egemen Pamukcu"
date: "3/3/2022"
output: html_document
---

## Loading Libraries
```{r}
library(tidyverse)
# install.packages("vtable")
library(vtable)
# install.packages("Hmisc")
library("Hmisc")
# install.packages("corrplot")
library(corrplot)
library(naniar)
library(corrplot)
library(stargazer)
library(htmltools)
```

## Loading Data
```{r}
df <- read_csv("../../data/final/small_data_imputed.csv")
output.fig.dir <- "../../output/figures"
output.tab.dir <- "../../output/tables"

SAVE.RESULTS = TRUE

df <- df %>% 
  rename(migrant_stock=ims_both_sex, 
         refugee_stock=estimated_refugee_stock_incl_asylum_seekers_both_sexes,
         disaster_displacement=disaster_stock_displacementr_raw,
         conflict_displacement=conflict_stock_displacement_raw, 
         climate_change=CCH, 
         air_quality=AIR, 
         rule_of_law=`value.Rule of Law: Estimate`, 
         gov_effectiveness=`value.Government Effectiveness: Estimate`, 
         corruption_control=`value.Control of Corruption: Estimate`,
         state_legit=`P1: State Legitimacy`, 
         cpa_d_12=D12, 
         cpa_d_avg=D_avg, 
         gdp=`GDP per capita (constant 2015 US$)`, 
         gini=`value.Gini index (World Bank estimate)`) %>% 
  mutate(conflict_displacement=conflict_displacement/10000, 
         disaster_displacement=disaster_displacement/10000,
         migrant_stock=migrant_stock/10000,
         refugee_stock=refugee_stock/10000,
         gdp=gdp/1000,
         state_legit=10-state_legit)

col_names <- c('migrant_stock'='Migrant Stock (10,000s)', 
               'refugee_stock'='Refugee Stock (10,000s)',
               'disaster_displacement'='Internal Displacement Due to Disasters (10,000s)',
               'conflict_displacement'='Internal Displacement Due to Conflict (10,000s)', 
               'climate_change'='Climate Change', 
               'air_quality'='Air Quality', 
               'rule_of_law'='Rule of Law', 
               'gov_effectiveness'='Government Effectiveness', 
               'corruption_control'='Control of Corruption',
               'state_legit'='State Legitimacy', 
               'cpa_d_12'='CPA: D-12', 
               'cpa_d_avg'='CPA: Cluster D Average', 
               'gdp'='GDP Per Capita (1,000s)', 
               'hdi_value'="HDI",
               'gini'="Gini Index") 

names(df)
```

## Descriptive Statistics
### Missingness
```{r}
vis_miss(df, sort_miss = T) + 
  ylab("Countries") + 
  theme(axis.text.y = element_blank(),
        axis.ticks.x = element_line(),
        panel.grid = element_blank(), 
        axis.text.x = element_text(angle=90))
  

if (SAVE.RESULTS) {
  ggsave(paste(output.fig.dir, '/missingness.png', sep=''), width = 5, height = 8)
}
```

### Summary Statistics
```{r}
sumtable(df, out='return')

if (SAVE.RESULTS) {
  sumtable(df, out='csv', file=paste(output.tab.dir, '/summary_table.csv', sep=''))
}
```


### Correlation Matrix
```{r}
df.rcorr <- df %>% 
  select(-iso, -country_name) %>% 
  as.matrix() %>% 
  rcorr()

corrplot(corr=df.rcorr$r,
         p.mat = df.rcorr$P,
         type='lower', insig='pch', sig.level =.1, pch.cex = .9, diag=F,
         tl.cex=.7, tl.col='black', tl.offset=.5, cl.pos='r', win.asp=1)

if (SAVE.RESULTS) {
  pdf(file=paste(output.fig.dir, '/corr_matrix.pdf', sep=''))
  corrplot(corr=df.rcorr$r,
           p.mat = df.rcorr$P,
           type='lower', insig='pch', sig.level =.1, pch.cex = .9, diag=F,
           tl.cex=.7, tl.col='black', tl.offset=.5, cl.pos='r', win.asp=1)
  dev.off()
}

```

```{r}
dist_plots <- lapply(names(df %>% select(-iso, -country_name)), function(var_x){
  p <- 
    ggplot(df) +
    aes_string(var_x) +
    theme_light() +
    theme(
      axis.text = element_blank(),
      axis.title.y = element_blank(),
      axis.title.x = element_text(family='Helvetica', size=9),
      axis.ticks = element_blank()
      )
    
  if(is.numeric(df[[var_x]])) {
    p <- p + geom_density()
  }
})


cowplot::plot_grid(plotlist = dist_plots)

if (SAVE.RESULTS) {
  ggsave(filename = paste(output.fig.dir, '/distributions.png', sep = ''))
}
```

### All countries
```{r}
lapply(names(df %>% select(-iso, -country_name, -state_legit)), 
          function(var_x){
              plt <- ggplot(df, aes_string(x=var_x, y='state_legit')) + 
              geom_point(colour='orange') +
              stat_smooth(method='lm', formula='y~x', fullrange=T, color='purple') + 
              ggrepel::geom_text_repel(label=df$iso) +
              theme_classic() + 
              labs(title=paste(col_names[var_x], 'vs.', 'State Legitimacy'))
              print(plt)
            
            if (SAVE.RESULTS) {
              ggsave(paste(output.fig.dir, '/state_legit_X_', var_x, '.png', sep=''))
            }
          }
       )
```

### Recipient Countries
```{r}
adb <- read_csv("../../data/final/adb-members.csv")
df.recip <- adb %>% 
  select(iso, donor) %>% 
  right_join(df, by='iso') %>% 
  filter(donor==0)

lapply(names(df.recip %>% select(-iso, -country_name, -state_legit, -donor)), 
          function(var_x){
              plt <- ggplot(df.recip, aes_string(x=var_x, y='state_legit')) + 
              geom_point(colour='orange') +
              stat_smooth(method='lm', formula='y~x', fullrange=T, color='purple') + 
              ggrepel::geom_text_repel(label=df.recip$iso) +
              theme_classic() + 
              labs(title=paste(col_names[var_x], 'vs.', 'State Legitimacy'), subtitle="Recipient Countries")
              print(plt)
            
            if (SAVE.RESULTS) {
              ggsave(paste(output.fig.dir, '/state_legit_X_', var_x, '_recipients', '.png', sep=''))
            }
          }
       )
```

### All Countries Except Afghanistan
```{r}

df.noafg <- df %>% filter(iso != 'AFG')

lapply(names(df.noafg %>% select(-iso, -country_name, -state_legit)), 
          function(var_x){
              plt <- ggplot(df.noafg %>% filter(iso != 'AFG'), aes_string(x=var_x, y='state_legit')) + 
              geom_point(colour='orange') +
              stat_smooth(method='lm', formula='y~x', fullrange=T, color='purple') + 
              ggrepel::geom_text_repel(label=df.noafg$iso) +
              theme_classic() + 
              labs(title=paste(col_names[var_x], 'vs.', 'State Legitimacy'))
              print(plt)
            
            if (SAVE.RESULTS) {
              ggsave(paste(output.fig.dir, '/state_legit_X_', var_x, '_NOAFG', '.png', sep=''))
            }
          }
       )
```


```{r}
climate.model <- lm(state_legit ~ climate_change + air_quality + hdi_value + gdp, df)
governance.model <- lm(state_legit ~ rule_of_law + gov_effectiveness + corruption_control + gdp, df)
migration.model <- lm(state_legit ~ migrant_stock + refugee_stock + conflict_displacement + disaster_displacement + gdp, df)
full.model <- lm(state_legit ~ rule_of_law + gov_effectiveness + corruption_control + migrant_stock + refugee_stock + conflict_displacement + disaster_displacement + climate_change + air_quality + hdi_value + gdp, df)

stargazer(climate.model, migration.model, governance.model, full.model, type='text')

if (SAVE.RESULTS) {
  stargazer(climate.model, migration.model, governance.model, full.model, type='html', out=paste(output.tab.dir, '/state_legit_reg.html', sep=''))
}

```

```{r}
climate.model <- lm(cpa_d_avg ~ climate_change + air_quality + hdi_value + gdp , df)
governance.model <- lm(cpa_d_avg ~ rule_of_law + gov_effectiveness + corruption_control + gdp , df)
migration.model <- lm(cpa_d_avg ~ migrant_stock + refugee_stock + conflict_displacement + disaster_displacement + gdp , df)
full.model <- lm(cpa_d_avg ~ rule_of_law + gov_effectiveness + corruption_control + migrant_stock + refugee_stock + conflict_displacement + disaster_displacement + climate_change + air_quality + hdi_value + gdp , df)

stargazer(climate.model, migration.model, governance.model, full.model, type='text')


if (SAVE.RESULTS) {
  stargazer(climate.model, migration.model, governance.model, full.model, type='html', out=paste(output.tab.dir, '/cpa_d_avg_reg.html', sep=''))
}

```

```{r}
climate.model <- lm(cpa_d_12 ~ climate_change + air_quality + hdi_value + gdp, df)
governance.model <- lm(cpa_d_12 ~ rule_of_law + gov_effectiveness + corruption_control + gdp, df)
migration.model <- lm(cpa_d_12 ~ migrant_stock + refugee_stock + conflict_displacement + disaster_displacement + gdp, df)
full.model <- lm(cpa_d_12 ~ rule_of_law + gov_effectiveness + corruption_control + migrant_stock + refugee_stock + conflict_displacement + disaster_displacement + climate_change + air_quality + hdi_value + gdp, df)

stargazer(climate.model, migration.model, governance.model, full.model, type='text')

if (SAVE.RESULTS) {
  stargazer(climate.model, migration.model, governance.model, full.model, type='html', out=paste(output.tab.dir, '/cpa_d_12_reg.html', sep=''))
}
```

